---
# tasks file for apache
- name: Ensure httpd packages are present
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ httpd_packages }}"
  notify: restart-apache-service
  tags:
     - rpm

- name: Ensure latest httpd.conf file is present for RPM
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify: restart-apache-service
  tags:
     - rpm

- name: Ensure latest httpd.conf file is present for Container
  template:
    src: httpd.conf.j2
    dest: /home/student1/ansible-for-devops-workshop/siteb/etc/httpd/conf/httpd.conf
  tags:
     - container

- name: Ensure latest index.html file is present for RPM
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  tags:
     - rpm

- name: Ensure latest index.html file is present for Container
  template:
    src: index.html.j2
    dest: /home/student1/ansible-for-devops-workshop/siteb/var/www/html/index.html
  tags:
     - container

- name: Ensure httpd service is started and enabled
  service:
    name: httpd
    state: started
    enabled: yes
  tags:
     - rpm
